### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by flamendless** [1bardesign/batteries#10]
Im using the latest version if batteries

```lua
require("batteries"):export()
print(mathx)
print(tablex)
print(stringx)
```

All outputs `nil`

**Comment by 1bardesign** [comment]
Fixed by 616b31b35f4036448042bf8362069c56454e29c4 ; specifically https://github.com/1bardesign/batteries/blob/master/init.lua#L55 - shouldn't happen again because of the refactor.
