### ISSUE TITLE
Use `type` as method instead of `string`

### ISSUE THREAD

**Issue by flamendless** [1bardesign/batteries#11]
Example in `vec2` module:

```lua
local pos = vec2:new()
print(pos:type()) -- error
```
most love libraries and even love userdata use `type` as a function instead of `string`, so maybe change it to
```lua
local pos = vec2:new()
print(pos:type()) --vec2
print(pos.__type) -vec2
```

This is probably more of a design choice, I'll be glad to know the your reasons behind it.

**Comment by 1bardesign** [comment]
At the moment it's mostly indecisiveness on how to integrate it with `class` - I'm not sure if something should be exposed per-class for allowing reflection on types. Reflection in general is something I'm not super hot on but in the absence of proper types in lua it's more or less what we're "stuck with".

I don't mind the idea of `class:type()` just returning `class.__type`.
I'm not sure how standard it is or what the rules are around __ prefix table members. Likely doesn't matter though as we're more or less "stuck with" luajit in love land.

On the performance front, having it as a method basically involves an extra function call over just a property access, which isn't great but ultimately unlikely to matter as you're rarely doing this in an ultra-performance-sensitive environment, and having the `__type` member would allow an escape hatch.
The tradeoff is more complicated in a JIT context too, haha - if the method was inlined it could end up faster than a property access in some situations.

I'll think about it. I can see merit to keeping familiarity with love users, but I think probably something needs to be added to `class` to facilitate it being standard.

**Comment by flamendless** [comment]
Okay I understand.

It was just a hardship earlier tracking why calling `pos.type()` errors haha.

**Comment by 1bardesign** [comment]
fixed in the recent class overhaul; `:type()` works for all `class`es (same syntax as love userdata so you don't need to typecheck even more ahead of time)
