### ISSUE TITLE
Table.clear error

### ISSUE THREAD

**Issue by flamendless** [1bardesign/batteries#2]
Line 147 in the assert function in table.lua (table.clear)

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by 1bardesign** [comment]
Nice catch on the typo. Would you be able to issue a pr with the fix? If you don't feel up to it no matter but I won't get to it til Monday at earliest and I imagine you would have fixed it locally.

**Comment by flamendless** [comment]
I was thinking of a PR but i thought it was too minor, anyways I'll do PR later

**Comment by 1bardesign** [comment]
Fixed by #3
