### ISSUE TITLE
colour.lua: hex_to_rgb

### ISSUE THREAD

**Issue by TurtleP** [1bardesign/batteries#26]
Something I noticed that could be useful in the `colour` namespace is a way to convert hex colors to rgb(a). Although not entirely common to do, it would be helpful as there's lots of predefined web colors, etc that use hex. Converting these to a float format [0, 1] is a pain.

For example, I often use [this color tool](https://material.io/resources/color/) when making a UI. It would be nice to say `colour.hex_to_rgba("#eeeeee")` and get the float values off of that.

Edit: I noticed there is `unpack_rgb` which takes a numerical value, although a string variant might be nice as well. Feel free to close, though, if you think it's not needed.

**Comment by 1bardesign** [comment]
The numeric value is faster to execute than the string, and you can use hex constants for inline unpacks. rgb, rgba and argb formats are supported.

I've thought about a cached interface that'd store the result of a hex lookup on access but I'm not sure it's really worth it. Could be nice with named colours too. I think auahdark might have something like that kicking around, I've never really needed it.

Will think about something like that, but I don't think the string one is worth much on its own, especially as it introduces ambiguity that'd need handling, like some folks using the hash prefix, some not, etc.
