### ISSUE TITLE
Docs improvement re package.path

### ISSUE THREAD

**Issue by eigenbom** [1bardesign/batteries#36]
On windows, using the basic lua5.1 interpreter, I had to add `package.path = package.path .. ";./?/init.lua"` before `require("ext.batteries"):export();` to get it to work. Could mention this on the Installation section?

**Comment by 1bardesign** [comment]
Fixed, suggestions welcome for any clearer wording :)

**Comment by eigenbom** [comment]
Thx Max :)

It looks like "./?/init.lua" wasn't added as a default in the interpreter until lua 5.3?

https://github.com/lua/lua/commit/124598917f4f314fdcb70a4165161999a645204e
