### ISSUE TITLE
Feature request: Intersection & difference table operations

### ISSUE THREAD

**Issue by speakk** [1bardesign/batteries#4]
Some basic set operations would be super handy:
- Intersection
- Difference
- Union (this is already possible with append + dedupe)

**Comment by 1bardesign** [comment]
I feel that I'd actually prefer a semi-"proper" set type for this, which would allow fast iteration of members (ie no pairs) but also avoid linear time additions as for `table.add_value` and similar. I'll need to think on it more. Definitely would be handy but needs a rock solid interface I think, and to avoid non-obvious performance caveats. Maybe `table` versions can be added as an interim measure though...
