### ISSUE TITLE
rgb_to_hsl h is unassigned

### ISSUE THREAD

**Issue by eigenbom** [1bardesign/batteries#43]
h is unassigned in this statement
https://github.com/1bardesign/batteries/blob/7767802433d5da947a663d104d8f5db2847e519a/colour.lua#L137

**Comment by 1bardesign** [comment]
it's used to define the local for the next section, but i'll move it to an explicit declaration to be more clear

**Comment by eigenbom** [comment]
Ah okay I missed that, cheers!
