### ISSUE TITLE
[Bug]: Subclass Not Updating Parent Variables

### ISSUE THREAD

**Issue by TurtleP** [1bardesign/batteries#46]
Hey,

I feel like my code is 99% correct, but for some strange reason, it isn't working properly. I have a subclass which extends a parent class, calls super for the necessary details, and then I try to move it around and allow the parent's draw method to handle rendering. However, it doesn't move. The only way for it to move is if I override the draw method and use the subclass's position variables. This doesn't make sense to me, since it should still be able to render at the position of the parent class, though. Here is the code I am using:

```lua
local peg = class()

peg.texture = love.graphics.newImage("graphics/objects.png")
peg.quads = {}
for index  = 1, 7 do
    peg.quads[index] = love.graphics.newQuad((index - 1) * 17, 0, 16, 16, peg.texture)
end

function peg:new(type, x, y)
    self.x = x
    self.y = y

    self.width = 16
    self.height = 16

    self.type = type
end

function peg:draw()
    love.graphics.draw(peg.texture, peg.quads[self.type], self.x * 16, self.y * 16)
end

function peg:move(x, y)
    self.x = self.x + x
    self.y = self.y + y
end

function peg:position()
    return self.x, self.y
end

function peg:__eq(other)
    return self.type == other.type
end

return peg
```

```lua
local peg = require((...):gsub("player", "peg"))
local player = class({extends = peg})

function player:new(x, y)
    self:super(1, x, y)
end

function player:movement(button)
    if button == "dpright" then
        self:move(1, 0)
    elseif button == "dpleft" then
        self:move(-1, 0)
    elseif button == "dpup" then
        self:move(0, -1)
    elseif button == "dpdown" then
        self:move(0, 1)
    end
    print(self:position(), self.x, self.y)
end

return player
```

Unless I'm meant to use the implements config, but that makes more sense for interfaced objects, which is not what I'm doing here. Hopefully I can get pointed to the right direction as to what is wrong.

To clarify a bit: printing the position in `peg:draw()` does show the initial values I load the player from, but they do not update from `player:movement()`. The values only change if I check inside the `player` class.

**Comment by TurtleP** [comment]
The comments do note:

```
class properties are not copied and should likely
be accessed through the concrete class object so
that everything refers to the same object
```

Though I don't think this is the issue here, at least as far as I can tell. If I refer to `self.x` in `player`, I'd think it would still refer to `peg`'s x value.

**Comment by 1bardesign** [comment]
I'm not convinced this is a batteries issue.

How are you constructing the object? This works for me:

```lua
local peg = class()

function peg:new(type, x, y)
    self.x = x
    self.y = y

    self.width = 16
    self.height = 16

    self.type = type
end

function peg:draw()
    print("peg", self:position())
end

function peg:move(x, y)
    self.x = self.x + x
    self.y = self.y + y
end

function peg:position()
    return self.x, self.y
end

local player = class({extends = peg})

function player:new(x, y)
    self:super(1, x, y)
end

function player:movement(button)
    if button == "dpright" then
        self:move(1, 0)
    elseif button == "dpleft" then
        self:move(-1, 0)
    elseif button == "dpup" then
        self:move(0, -1)
    elseif button == "dpdown" then
        self:move(0, 1)
    end
    print(self:position(), self.x, self.y)
end

local p = player(10, 10)
p:draw()
p:movement("dpright")
p:draw()
```
outputs:
```
peg     10      10
11      11      10
peg     11      10
```
sidenote: `print(self:position(), self.x, self.y)` is invalid as you can't use multi-return other than in the last place, which is why there's that weird inside issue.

I can imagine this could be caused by not constructing the player correctly, maybe?

**Comment by TurtleP** [comment]
Yeah, I figure something has to be wrong in my code, but I've legit looked at everything and don't see what it could be. The only place that *doesn't* show updated values is in the `draw` function. If I print `self.x` and `self.y` the player's coordinates never update, even though if I print them in `move` or the player's `movement` they do. Here's links to relevant code:

[map.lua for loading maps](https://github.com/TurtleP/Pegs/blob/dev/next/classes/game/map.lua#L40)
[peg.lua, base entity class for objects](https://github.com/TurtleP/Pegs/blob/dev/next/classes/game/pegs/peg.lua)
[player.lua, which is having the issue](https://github.com/TurtleP/Pegs/blob/dev/next/classes/game/pegs/player.lua)

**Comment by TurtleP** [comment]
Well, I *just* figured out the issue, my bad. Turns out that I forgot to make sure the player doesn't get reconstructed as a base entity peg in the `map:identify` function. I need more sleep haha. Again, apologies for raising a non-issue.
