### ISSUE TITLE
attempt to index a nil value (global 'love')

### ISSUE THREAD

**Issue by ramirobasile** [1bardesign/batteries#66]
Not sure if I'm doing this right, but I pulled batteries to my project and `require("batteries"):export()` would fail because love couldn't be found. I added a check for love at capture_callstacks part of async.lua and that did the trick.

Is it expected you pull in love for batteries to work?

**Comment by 1bardesign** [comment]
Can I have the full callstack for the error please?

I personally always use batteries from within love so that field is always available, but the intent is for it to work from plain lua as well where possible so I would like to fix it.

**Comment by ramirobasile** [comment]
Sure,

```
***@***.*** ~> mkdir test
***@***.*** ~> cd test
***@***.*** ~/test> git clone 
<https://github.com/1bardesign/batteries.git>
Cloning into 'batteries'...
remote: Enumerating objects: 1211, done.
remote: Counting objects: 100% (500/500), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 1211 (delta 384), reused 410 (delta 324), pack-reused 711
Receiving objects: 100% (1211/1211), 298.58 KiB | 1.64 MiB/s, done.
Resolving deltas: 100% (747/747), done.
***@***.*** ~/test> lua
Lua 5.3.6  Copyright (C) 1994-2020 Lua.org, PUC-Rio
 > require("batteries"):export()
./batteries/async.lua:32: attempt to index a nil value (global 'love')
stack traceback:
	./batteries/async.lua:32: in main chunk
	[C]: in function 'require'
	./batteries/init.lua:9: in local 'require_relative'
	./batteries/init.lua:37: in main chunk
	[C]: in function 'require'
	stdin:1: in main chunk
	[C]: in ?
```

Changing `if love.system.getOS() == 'Web' then` to `if love and 
love.system.getOS() == 'Web' then` at async.lua:32 solved it.

**Comment by 1bardesign** [comment]
yep have applied that fix, thanks :+1:
