### ISSUE TITLE
vec3:sset not using z properly

### ISSUE THREAD

**Issue by Yolwoocle** [1bardesign/batteries#73]
I believe there is a bug with the vec3:sset method.
```lua
function vec3:sset(x, y, z)
	self.x = x
	self.y = y or x
	self.z = z or y or z
	return self
end
```

Line 4. Shouldn't it be `z or y or x` instead?

**Comment by 1bardesign** [comment]
Yep it's a bug :)
I haven't used vec3 for a project recently so that's why it hasn't been caught.
