### ISSUE TITLE
Bilerp unused parameter.

### ISSUE THREAD

**Issue by Safebox36** [1bardesign/batteries#74]
Should line 75 be `v` instead of `u`? Otherwise the final parameter in this function goes unused.
https://github.com/1bardesign/batteries/blob/9b8ecf0e0d3c6573711dc29bcd2b1b22db720540/mathx.lua#L72-L78

**Comment by 1bardesign** [comment]
It doesn't, see the line below. the first pair of lerps are on u, then the result is lerped on v
